<?php
declare(strict_types=1);
namespace App\Facades;

use App\Services\Report\Fake\NbpApiResponse;

class NbpApiResponseFacade extends \Illuminate\Support\Facades\Facade
{
    protected static function getFacadeAccessor()
    {
        return NbpApiResponse::class; // TODO: Change the autogenerated stub
    }
}
