<?php
declare(strict_types=1);
namespace App\Facades;

use App\Services\Report\Fake\ReportWeeklyResult;

class ReportWeeklyResultFacade extends \Illuminate\Support\Facades\Facade
{
    protected static function getFacadeAccessor()
    {
        return ReportWeeklyResult::class; // TODO: Change the autogenerated stub
    }
}
